###################
#Bingo By Duckulus#
###################

# The Current Config Version. DO NOT CHANGE OR THINGS WILL BREAK
configVersion: 1.2

# The time before the game starts | DEFAULT=60
lobbyTime: 60
# The amount of Players required for the game to start | DEFAULT=2
minPlayers: 2
# The size of the WorldBorder | DEFAULT=10000
borderSize: 10000
# The time the timer skips to when forcestarting the game | DEFAULT=15
forcestartTime: 15
# The duration of the main phase of the game in seconds | DEFAULT=1800
gameDuration: 1800
# The Language that gets shown to players who use an unsupported Language | DEFAULT=en_us
defaultLocale: "en_us"
# Wether the size of teams should be limited based on the amount of players | DEFAULT=true
teamlimit: true
# If Pvp is enabled or not
pvp: false
# Wether the world should be wiped after the end of each round. It's recommended to turn this to true.
# WARNING: If you turn this to true on a server with an already thriving world without a backup it will be lost for ever!
worldReset: false
# How many teams should get a winning score before game ends
winningTeams: 1

items:
  - ACACIA_BOAT
  - ACACIA_DOOR
  - ACACIA_SIGN
  - AMETHYST_SHARD
  - APPLE
  - ARMOR_STAND
  - ARROW
  - AXOLOTL_BUCKET
  - BAKED_POTATO
  - BAMBOO
  - BEEF
  - BEETROOT
  - BEETROOT_SEEDS
  - BEETROOT_SOUP
  - BELL
  - BIRCH_BOAT
  - BIRCH_DOOR
  - BIRCH_SIGN
  - BLACK_CANDLE
  - BLACK_DYE
  - BLAZE_POWDER
  - BLAZE_ROD
  - BLUE_DYE
  - BONE
  - BONE_MEAL
  - BOOK
  - BOW
  - BOWL
  - BREAD
  - BREWING_STAND
  - BRICK
  - BROWN_DYE
  - BUCKET
  - BUNDLE
  - CAKE
  - CAMPFIRE
  - CARROT
  - CARROT_ON_A_STICK
  - CAULDRON
  - CHAIN
  - CHAINMAIL_BOOTS
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_HELMET
  - CHAINMAIL_LEGGINGS
  - CHARCOAL
  - CHEST_MINECART
  - CHICKEN
  - CLAY_BALL
  - CLOCK_00
  - COAL
  - COCOA_BEANS
  - COD
  - COD_BUCKET
  - COMPARATOR
  - COMPASS_00
  - COOKED_BEEF
  - COOKED_CHICKEN
  - COOKED_COD
  - COOKED_MUTTON
  - COOKED_PORKCHOP
  - COOKED_RABBIT
  - COOKED_SALMON
  - COOKIE
  - COPPER_INGOT
  - CRIMSON_DOOR
  - CRIMSON_SIGN
  - CYAN_DYE
  - DARK_OAK_BOAT
  - DARK_OAK_DOOR
  - DARK_OAK_SIGN
  - DIAMOND
  - DIAMOND_AXE
  - DIAMOND_BOOTS
  - DIAMOND_CHESTPLATE
  - DIAMOND_HELMET
  - DIAMOND_HOE
  - DIAMOND_HORSE_ARMOR
  - DIAMOND_LEGGINGS
  - DIAMOND_PICKAXE
  - DIAMOND_SHOVEL
  - DIAMOND_SWORD
  - DRIED_KELP
  - EGG
  - EMERALD
  - ENCHANTED_BOOK
  - ENDER_EYE
  - ENDER_PEARL
  - EXPERIENCE_BOTTLE
  - FEATHER
  - FERMENTED_SPIDER_EYE
  - FIREWORK_ROCKET
  - FIREWORK_STAR
  - FIRE_CHARGE
  - FISHING_ROD
  - FLINT
  - FLINT_AND_STEEL
  - FLOWER_POT
  - FURNACE_MINECART
  - GHAST_TEAR
  - GLASS_BOTTLE
  - GLISTERING_MELON_SLICE
  - GLOWSTONE_DUST
  - GLOW_BERRIES
  - GLOW_INK_SAC
  - GLOW_ITEM_FRAME
  - GOLDEN_APPLE
  - GOLDEN_AXE
  - GOLDEN_BOOTS
  - GOLDEN_CARROT
  - GOLDEN_CHESTPLATE
  - GOLDEN_HELMET
  - GOLDEN_HOE
  - GOLDEN_HORSE_ARMOR
  - GOLDEN_LEGGINGS
  - GOLDEN_PICKAXE
  - GOLDEN_SHOVEL
  - GOLDEN_SWORD
  - GOLD_INGOT
  - GOLD_NUGGET
  - GRAY_DYE
  - GREEN_DYE
  - GUNPOWDER
  - HEART_OF_THE_SEA
  - HONEYCOMB
  - HONEY_BOTTLE
  - HOPPER
  - HOPPER_MINECART
  - INK_SAC
  - IRON_AXE
  - IRON_BOOTS
  - IRON_CHESTPLATE
  - IRON_DOOR
  - IRON_HELMET
  - IRON_HOE
  - IRON_HORSE_ARMOR
  - IRON_INGOT
  - IRON_LEGGINGS
  - IRON_NUGGET
  - IRON_PICKAXE
  - IRON_SHOVEL
  - IRON_SWORD
  - ITEM_FRAME
  - JUNGLE_BOAT
  - JUNGLE_DOOR
  - JUNGLE_SIGN
  - KELP
  - KNOWLEDGE_BOOK
  - LANTERN
  - LAPIS_LAZULI
  - LAVA_BUCKET
  - LEAD
  - LEATHER
  - LIGHT_BLUE_DYE
  - LIGHT_GRAY_DYE
  - LIME_DYE
  - LINGERING_POTION
  - MAGENTA_DYE
  - MAGMA_CREAM
  - MAP
  - MELON_SEEDS
  - MELON_SLICE
  - MILK_BUCKET
  - MINECART
  - MUSHROOM_STEW
  - MUTTON
  - NAME_TAG
  - NAUTILUS_SHELL
  - NETHER_BRICK
  - NETHER_SPROUTS
  - NETHER_STAR
  - NETHER_WART
  - OAK_BOAT
  - OAK_DOOR
  - OAK_SIGN
  - ORANGE_DYE
  - PAINTING
  - PAPER
  - PHANTOM_MEMBRANE
  - PINK_DYE
  - POINTED_DRIPSTONE
  - POISONOUS_POTATO
  - PORKCHOP
  - POTATO
  - POTION
  - POWDER_SNOW_BUCKET
  - PRISMARINE_CRYSTALS
  - PRISMARINE_SHARD
  - PUFFERFISH
  - PUFFERFISH_BUCKET
  - PUMPKIN_PIE
  - PUMPKIN_SEEDS
  - PURPLE_DYE
  - QUARTZ
  - RABBIT
  - RABBIT_FOOT
  - RABBIT_HIDE
  - RABBIT_STEW
  - RAW_COPPER
  - RAW_GOLD
  - RAW_IRON
  - REDSTONE
  - RED_DYE
  - REPEATER
  - ROTTEN_FLESH
  - SADDLE
  - SALMON
  - SALMON_BUCKET
  - SCUTE
  - SEAGRASS
  - SEA_PICKLE
  - SHEARS
  - SHULKER_SHELL
  - SLIME_BALL
  - SNOWBALL
  - SOUL_CAMPFIRE
  - SOUL_LANTERN
  - SPECTRAL_ARROW
  - SPIDER_EYE
  - SPLASH_POTION
  - SPRUCE_BOAT
  - SPRUCE_DOOR
  - SPRUCE_SIGN
  - SPYGLASS
  - STICK
  - STONE_AXE
  - STONE_HOE
  - STONE_PICKAXE
  - STONE_SHOVEL
  - STONE_SWORD
  - STRING
  - SUGAR
  - SUGAR_CANE
  - SUSPICIOUS_STEW
  - SWEET_BERRIES
  - TNT_MINECART
  - TOTEM_OF_UNDYING
  - TRIDENT
  - TROPICAL_FISH
  - TROPICAL_FISH_BUCKET
  - TURTLE_EGG
  - TURTLE_HELMET
  - WARPED_DOOR
  - WARPED_FUNGUS_ON_A_STICK
  - WARPED_SIGN
  - WATER_BUCKET
  - WHEAT
  - WHEAT_SEEDS
  - WHITE_DYE
  - WOODEN_AXE
  - WOODEN_HOE
  - WOODEN_PICKAXE
  - WOODEN_SHOVEL
  - WOODEN_SWORD
  - WRITABLE_BOOK
  - WRITTEN_BOOK
  - YELLOW_DYE